name: schedule_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  responsive_framework: ^1.1.1
  intl: ^0.19.0
  # table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  get_storage: ^2.1.1
  syncfusion_flutter_calendar: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
flutter:
  uses-material-design: true